### PR TITLE
Add --tree-style-output compile option

### PR DESCRIPTION
**Pull request by roman8422**
Fixes issue #679

## Proposed Changes
Add an option to not create folders with target names and instead merge output_paths of all targets in one tree.

### CODE REVIEW

**Comment by uberspot** [comment]
Overall looks reasonable, but tests expect a different directory structure I believe so they should also be adjusted/fixed.

**Comment by ramaro** [comment]
Hey @roman8422 thanks for this - can you add a few test cases?

**Comment by roman8422** [comment]
> Hey @roman8422 thanks for this - can you add a few test cases?

Sure. I've had some personal stuff to deal with lately. Will fix this PR in the next couple of weeks.
Thanks for willingness to accept it.

**Comment by ramaro** [comment]
Hey @roman8422 any luck with this?

**Comment by roman8422** [comment]
@ramaro I pushed my latest code change but I can't make unit tests work on master branch before I even start writing tests for my code. Looks like it is related to this issue https://github.com/kapicorp/kapitan/issues/358.
Any advice how to overcome this?

**Comment by ramaro** [comment]
Thanks @roman8422 ! No problem, this is a known issue which we're fixing with the latest merges. I think this is good to go so merging. Thanks again

**Comment by ramaro** [comment]
@roman8422 you should be good to proceed now!

**Comment by roman8422** [comment]
@ramaro "Docker Build and Push" action is constantly failing. Is there something I can do to fix that?

**Comment by ramaro** [comment]
@roman8422 thanks for the patience. This looks good, thanks! Merging.

**Review by ramaro — APPROVED** [review]

**Comment by Roman-Clumio** [comment]
@ramaro I noticed that this PR wasn't merged and pushed a minor typo fix.
Any plans to merge it any time soon?

**Comment by ramaro** [comment]
@roman8422 apologies, I meant to merge this for v0.30 for missed it. Merging now so it will be official in v0.31. Thank you!

**Comment by ramaro** [comment]
@roman8422 actually no, sorry - spoke too soon as tests don't pass

**Pull request closed without merging**
