### PR TITLE
deps: upgrade jsonnet and gojsonnet to 0.20.0

### PR DESCRIPTION
**Pull request by antonincms**
Fixes issue #1005

## Proposed Changes

The related jsonnet changelog are :
- https://github.com/google/jsonnet/releases/tag/v0.18.0
- https://github.com/google/jsonnet/releases/tag/v0.19.0
- https://github.com/google/jsonnet/releases/tag/v0.19.1
- https://github.com/google/jsonnet/releases/tag/v0.20.0

Update search_imports function to return bytes according to the v0.19.0 changes mentioned there: https://github.com/google/jsonnet/releases/tag/v0.19.1

I hesitated whether to put bytes in cache directly or keeping current logic and encoding only at return.

### CODE REVIEW

**Review by MatteoVoges — APPROVED** [review]
lgtm :+1:

**Comment by antonincms** [comment]
I rebased the branch onto master and cleaned up unrelated import reordering that my IDE does.

**Comment by ramaro** [comment]
>I hesitated whether to put bytes in cache directly or keeping current logic and encoding only at return.

Thanks @antonincms - can you explain this further?

**Comment by antonincms** [comment]
@ramaro I was hesitant whether to put bytes in JSONNET_CACHE (and encode them only once), or encode when pulling from the cache (as currently done in the PR). I think the former is the simpler way, and I don't think encode should matter that much from a performance standpoint.

**Comment by ramaro** [comment]
thanks @antonincms !

**Pull request merged**
