### PR TITLE
feature: add new lower_alpha_num ref function

### PR DESCRIPTION
**Pull request by serapch**
## Proposed Changes

  - add lower_alpha_num ref function which generates string without any special characters or capital letters to be compliant with accountName of Azure StorageAccounts - https://docs.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create

### CODE REVIEW

**Comment by ramaro** [comment]
Hey @serapch thanks for this!

I know it's really just a nit, but in the interest of uniformity, can we rename the ref function to `loweralphanum`?

**Comment by ramaro** [comment]
Btw tests are failing but this is something being look at #828 and not related to this PR

**Comment by Cyanopus** [comment]
@serapch I would also remove the "sets it to ctx.data" in the secrets.md as these are implementation details that do not concern the users.

**Comment by serapch** [comment]
@ramaro I renamed the function and trimmed the unnecessary description :)

**Review by ramaro — APPROVED** [review]

**Comment by ramaro** [comment]
All good now, merging. Thank you @serapch

**Pull request merged**
